gm_projet:
    resource: "@GMProjetBundle/Resources/config/routing.yml"
    prefix:   /GM

utilisateurs:
    resource: "@UtilisateursBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"